config/routes.rb
FirehoseNew::Application.routes.draw do

  root 'static_pages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

def index

	@pics = Pic.all

end


def new 

@pic=Pic.new

end

def create
	@pic=Pic.create( pic_params )
	redirect_to pics_path
end


private

def pic_params
	params.require(:pic).permit(:learned, :emotion, :lesson, :image)
end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseNew</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-inverse">

  <div class="navbar-inner">

    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
  	  		<%= link_to 'Michael Segal', root_path, :class=>'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->

      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
  	  <ul class="nav">
  	  	<li>
  	  		<%= link_to 'LinkedIn','www.linkedin.com/in/michaelsegal' %>
  	  	</li>
  	  	<li>
  	  		<%= link_to 'Twitter','www.twitter.com/michaelsegal' %>
  	  	</li>
  	  	<li>
  	  		<%= link_to 'Curio Road','http://www.curioroad.com' %>
  	  	</li>
  	  	  	<li>
  	  		<%= link_to 'My App', pics_path %>
  	  	</li>
  	  	  	<li>
  	  		<%= link_to 'New Pic', new_pic_path %>
  	  	</li>

    </ul>

      </div>
 
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
<div class="span4 boxy text-center">
<h1 class="h1-custom">
	Lesson: <%= pic.lesson %><br>
</h1>
	<div class=h2-custom>Emotion: <%= pic.emotion %><br>
	Learned: <%= pic.learned %><br>
	Image: <%= image_tag pic.image %>
</div>
</div>
<% end %>

app/views/pics/new.html.erb
<div class="span6 offset4 text-center boxy">

<h1 class="h1-custom">
	Upload Another Lesson
</h1>

<%= simple_form_for @pic do |f|%>
	<%= f.input :lesson, :label => 'The Lesson', placeholder: '1'%>

<%= f.input :image, :label => 'Image' %>	

	<%= f.input :emotion, label: 'How Are You Feeling?', placeholder: 'Feeling Jazzed' %> 
	<%= f.input :learned, label: 'What Did You Learn?', placeholder: 'PostgresQL' %>
	<%= submit_tag "Save", :class=>'btn btn-info btn-large' %> 
<% end %>	

<div>

app/views/static_pages/index.html.erb
<div class="span6 offset4 boxy">

	<h1 class="h1-custom">Hi I'm Michael.</h1>
	<div class="boxybody">
	<h2 class="h2-custom">I'm currently a first year student at Harvard Business School.<br>I am also co-founder and CEO of Curio Road, an online marketplace for superstar handmade designers. Previously I worked at Bessemer Venture Partners, where I helped to invest in great startups such as Involver (acq by Oracle), Adap.tv (acq by AOL), and KupiVIP. </h2>

	<br>
<div class="boxybutton">
<%= link_to 'Get In Touch','mailto:michaelsegal72@gmail.com',:class=>'btn btn-info btn-large' %>

	<br><br>
	<div>
</div>
</div>